import { CreateDogDto } from 'src/dogs/dto/create-dog.dto';
import { CreateProductDto } from 'src/products/dto/createProduct.dto';

export const dogs: CreateDogDto[] = [
  {
    name: 'Max',
    sex: 'M',
    city: 'Bogotá',
    description: 'Muy amigable y juguetón.',
    imgUrl: 'https://example.com/dogs/dog1.jpg',
    status: true,
  },
  {
    name: 'Luna',
    sex: 'H',
    city: 'Medellín',
    description: 'Perfecto para familias con niños.',
    imgUrl: 'https://example.com/dogs/dog2.jpg',
    status: true,
  },
  {
    name: 'Rocky',
    sex: 'M',
    city: 'Cali',
    description: 'Le encanta correr en el parque.',
    imgUrl: 'https://example.com/dogs/dog3.jpg',
    status: true,
  },
  {
    name: 'Bella',
    sex: 'H',
    city: 'Cartagena',
    description: 'Tranquilo y cariñoso.',
    imgUrl: 'https://example.com/dogs/dog4.jpg',
    status: true,
  },
  {
    name: 'Simba',
    sex: 'M',
    city: 'Bogotá',
    description: 'Excelente guardián.',
    imgUrl: 'https://example.com/dogs/dog5.jpg',
    status: true,
  },
  {
    name: 'Nala',
    sex: 'H',
    city: 'Barranquilla',
    description: 'Busca un hogar lleno de amor.',
    imgUrl: 'https://example.com/dogs/dog6.jpg',
    status: true,
  },
  {
    name: 'Toby',
    sex: 'M',
    city: 'Pereira',
    description: 'Muy bien entrenado.',
    imgUrl: 'https://example.com/dogs/dog7.jpg',
    status: true,
  },
  {
    name: 'Lola',
    sex: 'H',
    city: 'Villavicencio',
    description: 'Sociable con otros animales.',
    imgUrl: 'https://example.com/dogs/dog8.jpg',
    status: true,
  },
  {
    name: 'Zeus',
    sex: 'M',
    city: 'Bucaramanga',
    description: 'Cariñoso y protector.',
    imgUrl: 'https://example.com/dogs/dog9.jpg',
    status: true,
  },
  {
    name: 'Maya',
    sex: 'H',
    city: 'Ibagué',
    description: 'Muy activo y curioso.',
    imgUrl: 'https://example.com/dogs/dog10.jpg',
    status: true,
  },
  {
    name: 'Thor',
    sex: 'M',
    city: 'Popayán',
    description: 'Amante de los paseos largos.',
    imgUrl: 'https://example.com/dogs/dog11.jpg',
    status: true,
  },
  {
    name: 'Coco',
    sex: 'M',
    city: 'Manizales',
    description: 'Le encanta nadar.',
    imgUrl: 'https://example.com/dogs/dog12.jpg',
    status: true,
  },
  {
    name: 'Bruno',
    sex: 'M',
    city: 'Neiva',
    description: 'Ideal para apartamentos.',
    imgUrl: 'https://example.com/dogs/dog13.jpg',
    status: true,
  },
  {
    name: 'Sasha',
    sex: 'H',
    city: 'Santa Marta',
    description: 'Inteligente y obediente.',
    imgUrl: 'https://example.com/dogs/dog14.jpg',
    status: true,
  },
  {
    name: 'Duke',
    sex: 'M',
    city: 'Cúcuta',
    description: 'Juguetón y lleno de energía.',
    imgUrl: 'https://example.com/dogs/dog15.jpg',
    status: true,
  },
];

export const products: CreateProductDto[] = [
  {
    name: 'Collar resistente',
    price: 83.07,
    imgUrl: 'https://example.com/products/product1.jpg',
    dogId: 1,
    status: true,
  },
  {
    name: 'Comida premium',
    price: 21.9,
    imgUrl: 'https://example.com/products/product2.jpg',
    dogId: 2,
    status: true,
  },
  {
    name: 'Pelota de goma',
    price: 84.0,
    imgUrl: 'https://example.com/products/product3.jpg',
    dogId: 3,
    status: true,
  },
  {
    name: 'Cama suave',
    price: 82.7,
    imgUrl: 'https://example.com/products/product4.jpg',
    dogId: 4,
    status: true,
  },
  {
    name: 'Juguete interactivo',
    price: 12.88,
    imgUrl: 'https://example.com/products/product5.jpg',
    dogId: 5,
    status: true,
  },
  {
    name: 'Correa extensible',
    price: 23.1,
    imgUrl: 'https://example.com/products/product6.jpg',
    dogId: 6,
    status: true,
  },
  {
    name: 'Ropa de invierno',
    price: 39.64,
    imgUrl: 'https://example.com/products/product7.jpg',
    dogId: 7,
    status: true,
  },
  {
    name: 'Champú hipoalergénico',
    price: 37.66,
    imgUrl: 'https://example.com/products/product8.jpg',
    dogId: 8,
    status: true,
  },
  {
    name: 'Comedero doble',
    price: 12.38,
    imgUrl: 'https://example.com/products/product9.jpg',
    dogId: 9,
    status: true,
  },
  {
    name: 'Cepillo para pelaje',
    price: 27.49,
    imgUrl: 'https://example.com/products/product10.jpg',
    dogId: 10,
    status: true,
  },
  {
    name: 'Galletas naturales',
    price: 35.66,
    imgUrl: 'https://example.com/products/product11.jpg',
    dogId: 11,
    status: true,
  },
  {
    name: 'Botella portátil de agua',
    price: 12.2,
    imgUrl: 'https://example.com/products/product12.jpg',
    dogId: 12,
    status: true,
  },
  {
    name: 'Juguete mordedor',
    price: 43.48,
    imgUrl: 'https://example.com/products/product13.jpg',
    dogId: 13,
    status: true,
  },
  {
    name: 'Arnés ajustable',
    price: 64.99,
    imgUrl: 'https://example.com/products/product14.jpg',
    dogId: 14,
    status: true,
  },
  {
    name: 'Toalla absorbente',
    price: 41.91,
    imgUrl: 'https://example.com/products/product15.jpg',
    dogId: 15,
    status: true,
  },
];
