// import { CreateDogDto } from 'src/dogs/dto/create-dog.dto';
// import { CreateProductDto } from 'src/products/dto/createProduct.dto';
// import { CreateUserDto } from 'src/users/dto/create-user.dto';

// export const dogs: CreateDogDto[] = [
//   {
//     name: 'Rocky',
//     sex: 'M',
//     city: 'Cali',
//     description: 'Le encanta correr en el parque.',
//     imgUrl:
//       'https://cloudfront-us-east-1.images.arcpublishing.com/elespectador/RLZTHM2WVBBNLKJAEILFK4KVEY.jpg',
//     status: true,
//   },
//   {
//     name: 'Bella',
//     sex: 'H',
//     city: 'Cartagena',
//     description: 'Tranquilo y cariñoso.',
//     imgUrl:
//       'https://res.cloudinary.com/dziccimdv/image/upload/v1750368912/qzbjainapl7efaunroc6.jpg',
//     status: true,
//   },
//   {
//     name: 'Simba',
//     sex: 'M',
//     city: 'Bogotá',
//     description: 'Excelente guardián.',
//     imgUrl: 'https://example.com/dogs/dog5.jpg',
//     status: true,
//   },
//   {
//     name: 'Nala',
//     sex: 'H',
//     city: 'Barranquilla',
//     description: 'Busca un hogar lleno de amor.',
//     imgUrl: 'https://example.com/dogs/dog6.jpg',
//     status: true,
//   },
//   {
//     name: 'Toby',
//     sex: 'M',
//     city: 'Pereira',
//     description: 'Muy bien entrenado.',
//     imgUrl: 'https://example.com/dogs/dog7.jpg',
//     status: true,
//   },
//   {
//     name: 'Lola',
//     sex: 'H',
//     city: 'Villavicencio',
//     description: 'Sociable con otros animales.',
//     imgUrl: 'https://example.com/dogs/dog8.jpg',
//     status: true,
//   },
//   {
//     name: 'Zeus',
//     sex: 'M',
//     city: 'Bucaramanga',
//     description: 'Cariñoso y protector.',
//     imgUrl: 'https://example.com/dogs/dog9.jpg',
//     status: true,
//   },
//   {
//     name: 'Maya',
//     sex: 'H',
//     city: 'Ibagué',
//     description: 'Muy activo y curioso.',
//     imgUrl: 'https://example.com/dogs/dog10.jpg',
//     status: false,
//   },
//   {
//     name: 'Thor',
//     sex: 'M',
//     city: 'Popayán',
//     description: 'Amante de los paseos largos.',
//     imgUrl: 'https://example.com/dogs/dog11.jpg',
//     status: false,
//   },
//   {
//     name: 'Coco',
//     sex: 'M',
//     city: 'Manizales',
//     description: 'Le encanta nadar.',
//     imgUrl: 'https://example.com/dogs/dog12.jpg',
//     status: true,
//   },
//   {
//     name: 'Bruno',
//     sex: 'M',
//     city: 'Neiva',
//     description: 'Ideal para apartamentos.',
//     imgUrl: 'https://example.com/dogs/dog13.jpg',
//     status: true,
//   },
//   {
//     name: 'Sasha',
//     sex: 'H',
//     city: 'Santa Marta',
//     description: 'Inteligente y obediente.',
//     imgUrl: 'https://example.com/dogs/dog14.jpg',
//     status: true,
//   },
//   {
//     name: 'Duke',
//     sex: 'M',
//     city: 'Cúcuta',
//     description: 'Juguetón y lleno de energía.',
//     imgUrl: 'https://example.com/dogs/dog15.jpg',
//     status: true,
//   },
// ];

// export const products: CreateProductDto[] = [
//   {
//     name: 'Collar resistente',
//     price: 83.07,
//     imgUrl: 'https://example.com/products/product1.jpg',
//     status: true,
//   },
//   {
//     name: 'Comida premium',
//     price: 21.9,
//     imgUrl: 'https://example.com/products/product2.jpg',
//     status: true,
//   },
//   {
//     name: 'Pelota de goma',
//     price: 84.0,
//     imgUrl: 'https://example.com/products/product3.jpg',
//     status: true,
//   },
//   {
//     name: 'Cama suave',
//     price: 82.7,
//     imgUrl: 'https://example.com/products/product4.jpg',
//     status: true,
//   },
//   {
//     name: 'Juguete interactivo',
//     price: 12.88,
//     imgUrl: 'https://example.com/products/product5.jpg',
//     status: true,
//   },
//   {
//     name: 'Correa extensible',
//     price: 23.1,
//     imgUrl: 'https://example.com/products/product6.jpg',
//     status: true,
//   },
//   {
//     name: 'Ropa de invierno',
//     price: 39.64,
//     imgUrl: 'https://example.com/products/product7.jpg',
//     status: true,
//   },
//   {
//     name: 'Champú hipoalergénico',
//     price: 37.66,
//     imgUrl: 'https://example.com/products/product8.jpg',

//     status: true,
//   },
//   {
//     name: 'Comedero doble',
//     price: 12.38,
//     imgUrl: 'https://example.com/products/product9.jpg',
//     status: true,
//   },
//   {
//     name: 'Cepillo para pelaje',
//     price: 27.49,
//     imgUrl: 'https://example.com/products/product10.jpg',
//     status: true,
//   },
//   {
//     name: 'Galletas naturales',
//     price: 35.66,
//     imgUrl: 'https://example.com/products/product11.jpg',
//     status: true,
//   },
//   {
//     name: 'Botella portátil de agua',
//     price: 12.2,
//     imgUrl: 'https://example.com/products/product12.jpg',
//     status: true,
//   },
//   {
//     name: 'Juguete mordedor',
//     price: 43.48,
//     imgUrl: 'https://example.com/products/product13.jpg',
//     status: true,
//   },
//   {
//     name: 'Arnés ajustable',
//     price: 64.99,
//     imgUrl: 'https://example.com/products/product14.jpg',
//     status: true,
//   },
//   {
//     name: 'Toalla absorbente',
//     price: 41.91,
//     imgUrl: 'https://example.com/products/product15.jpg',
//     status: true,
//   },
// ];

// export const users: CreateUserDto[] = [
//   {
//     name: 'Juan Pérez',
//     email: 'juan.perez@example.com',
//     password: 'Password123',
//     phone: '3001234567',
//   },
//   {
//     name: 'María Rodríguez',
//     email: 'maria.rodriguez@example.com',
//     password: 'SecurePass1',
//     phone: '3002345678',
//   },
//   {
//     name: 'Carlos Gómez',
//     email: 'carlos.gomez@example.com',
//     password: 'StrongOne2',
//     phone: '3003456789',
//   },
//   {
//     name: 'Laura Sánchez',
//     email: 'laura.sanchez@example.com',
//     password: 'MyPassWord3',
//     phone: '3004567890',
//   },
//   {
//     name: 'Andrés Torres',
//     email: 'andres.torres@example.com',
//     password: 'SuperSafe4',
//     phone: '3005678901',
//   },
//   {
//     name: 'Diana López',
//     email: 'diana.lopez@example.com',
//     password: 'AlphaBeta5',
//     phone: '3006789012',
//   },
//   {
//     name: 'Fernando Ruiz',
//     email: 'fernando.ruiz@example.com',
//     password: 'Better1234',
//     phone: '3007890123',
//   },
//   {
//     name: 'Catalina Mora',
//     email: 'catalina.mora@example.com',
//     password: 'TrustMe6a',
//     phone: '3008901234',
//   },
//   {
//     name: 'Luis Méndez',
//     email: 'luis.mendez@example.com',
//     password: 'SafePass7',
//     phone: '3009012345',
//   },
//   {
//     name: 'Paula Castillo',
//     email: 'paula.castillo@example.com',
//     password: 'Powerful8a',
//     phone: '3010123456',
//   },
//   {
//     name: 'Esteban Jiménez',
//     email: 'esteban.jimenez@example.com',
//     password: 'MySecret9',
//     phone: '3011234567',
//   },
//   {
//     name: 'Lucía Vargas',
//     email: 'lucia.vargas@example.com',
//     password: 'CoolKey10a',
//     phone: '3012345678',
//   },
//   {
//     name: 'Diego Castaño',
//     email: 'diego.castano@example.com',
//     password: 'Password11A',
//     phone: '3013456789',
//   },
//   {
//     name: 'Sara Martínez',
//     email: 'sara.martinez@example.com',
//     password: 'SecureMe12',
//     phone: '3014567890',
//   },
//   {
//     name: 'Jorge Herrera',
//     email: 'jorge.herrera@example.com',
//     password: 'UpDown13a',
//     phone: '3015678901',
//   },
// ];
